core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', 'accounts')),
    path('', include('ecommerce.urls', 'ecommerce'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

ecommerce/urls.py
from django.urls import path

from . import views 

app_name = 'ecommerce'

urlpatterns = [
    path('', views.HomeView.as_view(), name='HomeView'),
    path('cart/', views.CartView.as_view(), name='CartView'),
    path('cart/add/<int:product_id>/', views.AddToCartView.as_view(), name='AddToCartView'),
    path('cart/del/<int:product_id>/', views.DeleteFromCart.as_view(), name='DeleteFromCartView'),
    path('cart/pay', views.PayView.as_view(), name='PayView'),

    # this a Product instance creater, you can use this to create some fake data for test 
    # consider deleting this and it's view from views.py if you want to create products manualy 
    path('produce_data_for_test/', views.ProduceDataView.as_view(), name='ProduceDataView'),
]

ecommerce/models.py
from django.db import models
from accounts.models import Profile
from django.core.validators import MinValueValidator
from django.utils.safestring import mark_safe

class Product(models.Model):

    title = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    stock = models.IntegerField(default=0, validators=[MinValueValidator(0, 'must be greater than zero')])
    price = models.DecimalField(validators=[MinValueValidator(0)] , max_digits=10, decimal_places=2) 
    image = models.ImageField(upload_to='products', default='products/default-product.jpeg')

    def __str__(self):
        return f'{self.title}'
    

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" width="150" height="150" />')


    def decrease_stock(self ,by=1):
        if self.stock < by :
            return None
        self.stock -= by 
        self.save()
        return self.stock


class Order(models.Model):
    
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='orders')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='orders', null=True)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1, 'must be greater than one')])
    created_date = models.DateField(auto_now_add=True)

    payed = models.BooleanField(default=False)

    def get_total_price(self):
        return self.quantity * self.product.price

    def mark_as_payed(self):
        self.payed = True
        self.save()
        return self.payed

ecommerce/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class AddToCartForm(forms.Form):

    quantity = forms.IntegerField(min_value=1, max_value=10)

    def __init__(self, *args, **kwargs):
        # Receive additional parameters in the constructor
        action_url = kwargs.pop('action_url', None)
        super(AddToCartForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        # Set the form action dynamically
        if action_url:
            self.helper.form_action = action_url

        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit', css_class='w-100'))


class DeleteFromCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10)

    def __init__(self, *args, **kwargs):
        # Receive additional parameters in the constructor
        action_url = kwargs.pop('action_url', None)
        super(DeleteFromCartForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        # Set the form action dynamically
        if action_url:
            self.helper.form_action = action_url

        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))

ecommerce/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from django import http, views
from django.http import HttpResponse
from .models import Product, Order
from .cart import Cart
from .forms import AddToCartForm, DeleteFromCartForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


class HomeView(views.View):

    template_name = 'ecommerce/home.html' 

    def get(self, request):
        products = Product.objects.all()

        data_pack = {}
        
        for product in products:
            to_url = 'cart/add/' + str(product.id) + '/'
            data_pack[product] = AddToCartForm(action_url = to_url)
            

        context = {
            'data_pack' : data_pack,
        }

        return render(request, self.template_name, context)



class CartView(views.View):

    template_name = 'ecommerce/cart.html'  

    def get(self, request):
        return render(request, self.template_name)


class AddToCartView(views.View):

    def post(self, request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        form = AddToCartForm(request.POST)
        cart = Cart(request)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
            messages.success(request, 'Added To your Cart, You can see and pay for it in cart page you can access it from navbar')
        return redirect('ecommerce:HomeView')
    
class DeleteFromCart(views.View):

    def post(self, request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        cart = Cart(request)
        cart.delete(product)

        return redirect('ecommerce:CartView')
        

class PayView(views.View):

    def dispatch(self, request ,*args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, f'you need to Login First')                
            return redirect('ecommerce:CartView')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        cart = Cart(request)

        for product_id , product in cart:
            p = get_object_or_404(Product, pk=product_id)
            if p.stock < product['quantity'] :
                messages.error(request, f'you ordered product "{p.title}" more than current stock')                
                return redirect('ecommerce:CartView')

        for product_id , product in cart:
            p = get_object_or_404(Product, pk=product_id)
            o = Order.objects.create(
                profile = request.user.profile,
                product = p,
                quantity = product['quantity'],
            )   
            o.mark_as_payed()     
            p.decrease_stock(o.quantity)

        cart.empty()
        messages.success(request, 'Successfull, you can see list of products you bought on User Dashboard')
        return redirect('ecommerce:CartView')








# this view is for producing initial datas you can delete this and it's url path in urls.py
# if you want to create products manually
from .produce_data import produce_data

class ProduceDataView(views.View):

    def get(self, request):
        produce_data.produce()
        return redirect('ecommerce:HomeView')

ecommerce/templates/ecommerce/cart.html
{% extends "layouts/index.html" %}
{% load ecommerce_extras %}


{% block title %}Cart{% endblock title %}

{% block body_tag %}
    {% include "components/nav.html" %}

    <div class="container">
        <div class="card mt-5">
            <div class="card-header">
                Cart Info
            </div>
            <div class="card-body">
                <table class="table table-striped mt-5" >
                    <thead>
                        <tr class="table-dark">
                            <th scope="col">title</th>
                            <th scope="col">quantity</th>
                            <th scope="col">price per 1</th>
                            <th scope="col">total price</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody> 
                        {% for product_id, product in cart%}
                        <tr>
                            <td>{{ product.title }}</td>
                            <td>{{ product.quantity }}</td>
                            <td>{{ product.price }}$</td>
                            <td>{{ product.price | multiply:product.quantity }}$</td>
                            <td scope="col">
                                <form method="post" action="{% url "ecommerce:DeleteFromCartView" product_id %}">
                                    {% csrf_token %}
                                    <input type="submit" name="submit" class="btn btn-danger w-100" value="Delete">
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        <tr class="table-success ">
                            <td>Total</td>
                            <td>{{ cart|length }}</td>
                            <td>-</td>
                            <td> {{ cart.get_total_price }}$ </td>
                            <td>
                                <form action="{% url "ecommerce:PayView" %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Pay" class="btn btn-primary w-100" >
                                </form> 
                            </td>
                        </tr>
                    </tbody>
                </table>

                {% include "components/message.html" %}

            </div>

        </div>
     
    </div>

{% endblock body_tag %}

ecommerce/templates/ecommerce/home.html
{% extends "layouts/index.html" %}

{% block title %} Home {% endblock title %}

{% block body_tag %}
    {% include "components/nav.html" %}
    <div class="container vh-100">
        <div class="jumbotron text-center mt-3">
            <h1 class="display-4">Welcome to our E-commerce store!</h1>
            <p class="lead">Explore our wide range of products and find the best deals.</p>
        </div>
        {% include "components/message.html" %}
        <!-- Fancy Product Cards -->
        <div class="row">
            {% for product, form in data_pack.items  %}
                {% include "components/product.html" %}
            {% empty %}

                <a href="{% url "ecommerce:ProduceDataView" %}" class="btn btn-warning"> Produce some Products </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock body_tag %}