accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.RegisterView.as_view(), name='RegisterView'),
    path('login/', views.LoginView.as_view(), name='LoginView'),
    path('logout/', views.LogoutView.as_view(), name='LogoutView'),
    path('dashboard/', views.DashboardView.as_view(), name='DashboardView'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', 'accounts')),
    path('', include('ecommerce.urls', 'ecommerce'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

ecommerce/urls.py
from django.urls import path

from . import views 

app_name = 'ecommerce'

urlpatterns = [
    path('', views.HomeView.as_view(), name='HomeView'),
    path('cart/', views.CartView.as_view(), name='CartView'),
    path('cart/add/<int:product_id>/', views.AddToCartView.as_view(), name='AddToCartView'),
    path('cart/del/<int:product_id>/', views.DeleteFromCart.as_view(), name='DeleteFromCartView'),
    path('cart/pay', views.PayView.as_view(), name='PayView'),

    # this a Product instance creater, you can use this to create some fake data for test 
    # consider deleting this and it's view from views.py if you want to create products manualy 
    path('produce_data_for_test/', views.ProduceDataView.as_view(), name='ProduceDataView'),
]

templates/components/message.html
{% if messages %}
    {% for message in messages %}
    <div class="{{message.tags}} mt-3" role="alert">
        {{ message }}
      </div>
    {% endfor %}
{% endif %}

templates/components/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
    <a class="navbar-brand" href="{% url "ecommerce:HomeView" %}">E-commerce</a>
    <div>
    {% if request.user.is_authenticated %}
            <a href="{% url "accounts:LogoutView" %}" class="btn btn-danger">Logout</a>
            <a class="btn btn-warning" href="{% url "accounts:DashboardView" %}" > {{request.user.email}}</a>
    {% else %}    
            <a href="{% url "accounts:LoginView" %}" class="btn btn-primary">Login</a>
            <a href="{% url "accounts:RegisterView" %}" class="btn btn-danger">Register</a>
    {% endif %}
            <a href="{% url "ecommerce:CartView" %}" class="btn btn-secondary">cart {{ cart|length }}</a>
    </div>
    </div>
</nav>

templates/components/product.html
{% load static %}
{% load crispy_forms_tags %}
<div class="col-md-4 mb-4">
    <div class="card">
        <img src="{{ product.image.url }}" class="card-img-top" alt="Product Image">
        <div class="card-body">
            <h5 class="card-title">{{ product.title }}</h5>
            <p class="card-text">{{ product.description | truncatechars:140 }}</p>
            {% comment %} <form action="{% url "ecommerce:AddToCartView" product.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary">
            </form> {% endcomment %}
            
            {% crispy form %}
            {% if product.stock %}
                <div class="alert alert-success text-center">
                    <h3>
                        only {{ product.stock }} Left
                    </h3>
                </div>
            {% else %}
                <div class="alert alert-danger text-center">
                    <h3>
                        nothing left
                    </h3>
                </div>
            {% endif %}
        </div>
    </div>
</div>